### ISSUE TITLE
What's the "predict the class label of the center pixel"?

### ISSUE THREAD

**Issue by Bonsen** [Kamnitsask/deepmedic#101]
The network in ur paper - "Efficient multi-scale 3D CNN with fully connected CRF for accurate brain lesion segmentation" is predicting the class label of the center pixel (another is predicting the class label for the entire patch) and I don't really understand what is "predict the class label of the center pixel".

For example,

in training, if I input a 48x48x48 train patch and a 48x48x48 label patch in one "predicting the class label of the center pixel" network, after some conv layers, it may output  a 40x40x40 train patch, so I have to crop label patch to 40x40x40 surround center pixel for input?

and in testing, if I also need to add some background pixels surround the test image? Like the training, I need to add 8 pixel surround the the image?
if add 1 pixel, like :
0 0 0 0 0 0
0 2 2 2 2 0
0 2 2 2 2 0
0 0 0 0 0 0

**Comment by Kamnitsask** [comment]
Hi Bonsen,

I think you are a bit confused. Let me try clarify. DeepMedic is a type of fully-convolutional network (see section 2.1, eg after Eq.2., and figures 2,5). It is not predicting the center pixel of the input, which older patch-wise classifier networks did (see literature review). DM is predicting the central-"part" of the input, just like any fully convolutional net. "Part", instead of the whole patch, because DM is not using padding, so the output is going to be smaller than the input. Eg for input at 1st scale = 25^3 you get 9^3 output segmented voxels.

You dont need to add extra padding. Extra padded at the edges of the image is added automatically when the option "padInputImagesBool = True" in trainConfig, which is the case by default. When it's on, at every side of the input image (not input to the net, which are segments/subvolumes, but the whole image).

Hope the above helps.
K

**Comment by maylad31** [comment]
And sir each voxel of the central part is predicted with each shift of the receptive field over the input.Am I right?

**Comment by Kamnitsask** [comment]
Yeap, this sounds correct maylad31

**Comment by maylad31** [comment]
Thank you so much sir.
