### ISSUE TITLE
How do you get the segmentation map from probabilities maps?

### ISSUE THREAD

**Issue by pykao** [Kamnitsask/deepmedic#105]
Hello Konstantinos,
I am working brain tumor segmentation by using original deepmedic on BRATS2015 database. I noticed that in the boundary of label 1 (Nercosis) and label 2 (edema), the probability of label 3 (Non-enhancing tumor) which is 0.0.4465 is much higher than the probability of label 1 (0.4046) and label 2(0.1428). However, you still assign label 2 with the lowest probability to that boundary voxel.
![example](https://user-images.githubusercontent.com/26263963/38648752-c75fa942-3da7-11e8-98c4-abd4caf8dd26.png)
![example2](https://user-images.githubusercontent.com/26263963/38648937-baedf4a6-3da8-11e8-9048-a0342837314f.png)

I think you suppose to give a label with the highest probability to that voxel. But this is not the case I observe on these two subjects. And although there are some voxels with the highest probability for label 3, but I am not able to find any label 3 within these two subjects. 
Did I do something wrong? or Did you do any postprocessing to create the segmentation maps?

Best, 
Po-Yu

**Comment by Kamnitsask** [comment]
Hello,

Segmentation is created with argmax on the probability maps.

./deepMedic/routines/testing.py -> function performInferenceOnWholeVolumes(...)
L305 starts the part where predictions are being saved.
Segmentations are created from probability maps calling argmax( ) at line L307.

I cannot answer with confidence what is the cause of what you observed, but I would guess this could be caused by the viewer software, which may be intepolating between values in order to visualise better certain points. If you want to be certain, you could load those values within numpy/matlab/etc, not from a viewer, and double check if this still happens.

**Comment by Kamnitsask** [comment]
Related to issue #104
