### ISSUE TITLE
What Is Difference Between The Results Of Your Article And Your Results On MICCAI Site?

### ISSUE THREAD

**Issue by ZeinabSalkhorde** [Kamnitsask/deepmedic#108]
Dear Kamnitsask.
 I used your software available at https://github.com/Kamnitsask/deepmedic. In this regard, I trained BRATS 2015 and ISLES 2015. I evaluated the BRATS Testing 2015 and  SISS Testing 2015 data using these two links below:
https://www.smir.ch/BRATS/EvaluationchallengeType=BRATS2015TestingV2.
https://www.smir.ch/ISLES/Evaluation?challengeType=ISLES2015SISSTesting.
1. The results I got through the evaluation on the site are not the same with the evaluation results using your code. What is the reason for this?

2. The results recorded for your work for  BRATS 2015 Testing and ISLES 2015 SISS Testing on the https://www.smir.ch/BRATS/Start2015 and http://www.isles-challenge.org/ISLES2015/#02  are different from those reported in the "DeepMedic for Brain Tumor Segmentation" and "Efficient Multi-Scale 3D CNN with Fully Connected CRF for Accurate Brain Lesion Segmentation" article.
What is the reason for this difference?

Thanks for your attention.
Zeinab Salkhorde

**Comment by Kamnitsask** [comment]
Hello,

1. If I understand correctly, you are asking why the DSC reported in the logs of deepmedic may be different from the DSC reported by the evaluation platform. One possible reason that comes in mind is how cases that do not have a class at all are handled by the code. My own scripts take these cases as N/A, and do not include them in the calculation of the mean. The online evaluation platform is including them in the mean as zeros (at least it used to, I guess thats still the case). In our journal paper, we report the numbers calculated exactly as the evaluation platform (including them as zeros), to be consistent with the platform (footnote 3 at page 10 of the journal). In the logs, I report them as N/A, because I find it more appropriate. There may be other reasons, eg sometimes I remember the online platform was not appropriately receiving all files when batch uploaded, and they needed to be reuploaded, but I do not know if this was solved since 2 years ago when I worked with it.

2. (BRATS15) There is indeed difference between the numbers for my own entry in the evaluation platform of BRATS2015 and the numbers recorded in our journal paper, which is simply because the evaluation platform is/can be updated any time with simply re-uploading different experiments, eg if one wants to try something else/new. I do not remember what the last experiments I uploaded were. In various occasions I thought I should reupdate them with the best model to avoid such confusions, but they are bound to change at any point if I chose to try other stuff. So my own suggestion (for comparing with any work) is to always use the published+peer reviewed results as reference, the rest change without notice.

2. (ISLES) There are no differences between numbers on the journal and the evaluation platform, not for the training nor the testing set as far as I can tell. Can you point me specific to which disctrepancies you meant?

Hope the above clarify things.

**Comment by ZeinabSalkhorde** [comment]
Dear Kostas
Thanks very much for your complete answer.I understand  your meaning, and the results, as you mentioned, were the same for ISLES.Thanks again.
Best,
Zeinab Salkhorde
