### ISSUE TITLE
Non-binary ROI masks

### ISSUE THREAD

**Issue by OdelinCharron** [Kamnitsask/deepmedic#111]
Hello Konstantinos !

I would like to report something, I don't know if it's a known ''issue'' or if it's normal...

If you don't use a binary ROI mask deepmedic seems to increase the number of classes by himself.

For example :
If the number of classes is 2 (numberOfOutputClasses = 2)
And the number of classes in the ROI mask is also 2.
You will get two probability maps and a segmentation map.
But the segmentation map can contain up to 4 classes.

If it's not a bug I think I should get 4 probability maps, but I don't know why I get only two of them 
(Actually I think the probability map-0 is the pseudo proba of classes 0 and 2 and the second probability map is for the classes 1 and 3)

But if it's a bug a quick solution could be to add a binarization step during the opening of the ROI masks.
If it's a bug I would go with an option asking to the user if he want to use binarized masks.

Best,
Odelin.

PS : Good job for deepmedic, it's so nice !

**Comment by Kamnitsask** [comment]
Sounds like a bug indeed.

As far as I remember, I always assumed a binary ROI mask when designing it (and currently can't think reasons for a non-binary ROI mask.).

To be honest, I kinda hesitate to make assumptions in the code such as (if multiclass ROI, I should just binarise it under the hood), as it may not be what the user really intended. Sometimes getting an obvious error is better, so that the user becomes aware and adapts what the input they provide.

I will keep this issue open to have a look what happens in the code, in case I can handle it better, eg with a proper message/question to user.

For now, please leave this issue open. And thanks a lot for bringing it to my attention.

K
