### ISSUE TITLE
about optimizing this project based on personal idea

### ISSUE THREAD

**Issue by dzfowen** [Kamnitsask/deepmedic#120]
Hi researchers,  I am going to optimize your project on my idea, for example change neural model or some processing details, therefore I need to understand your programming. Is there any suggestions for me to do that?

Thanks a lot!

**Comment by Kamnitsask** [comment]
Although this issue tracker is not for this type of questions, I will give it a try :

1. You will need to read our MedIA paper (see doc) to understand the architecture and training process, so that you understand what is happening in the code.
2. You will need good understanding of Tensorflow. If you are not adept in it, I strongly suggest you start with a tutorial in tensorflow, learn how to use it, and only then dive into DM's code to alter it.
3. Just with any non-trivial codebase, you will need patience. You will need to follow the flow of control in the code, from the front end to the back end:
Start with ./deepMedicRun that is the entry point.
Continue with the call to trainSession. This internally creates the model architecture and afterwards starts the training routine. Following the calls in there will lead you to delve into how the architecture is created into cnn3d, pathways, layers. And then they will take you to the training routine, which itself has substructure.

In order to make DM possible to train/test as an out-of-the-box tool even for non ML practicioners, the codebase is not trivial as straightforward 100-lines CNNs. So make sure you go slowly into it and get its design. If your aim is to focus on the ML side of things, perhaps starting from a cleaner starting point with a standard DL library and implement your own thing may be a better starting point, as it will allow you to learn DL from scratch. This all depends on your ultimate aims.

At this point I ll close this issue, as this issue tracker is more for tracking bugs and problems with the codebase, not for such "discussions". Feel free to send me an email if you d like to discuss such things at a later timepoint, and I ll try to be responsive.

Cheers,
K
