### ISSUE TITLE
Inference channels in "testConfig.cfg"

### ISSUE THREAD

**Issue by alicebeauti** [Kamnitsask/deepmedic#127]
Hi Konstantinos,

Thank you for posting such a nice work here. Really amazed by the power of your architecture.

I found an interesting point when I perform the testing on the brats datasets and my own datasets. Just for illustration purpose, I am using testConfig.cfg file as configuration for testing on the brats datasets. Inside this file, there is one place to define how many channels are being used for inputs as shown below.
channels = ["./testChannels_flair.cfg", "./testChannels_t1c.cfg"]

I found that the trained model will provide different segmentation masks if I switch the order of the channels list files like what is shown below.
channels = [ "./testChannels_t1c.cfg","./testChannels_flair.cfg"]

Supposedly, if the model reads the whole two lists from the channels, the inferred mask shouldn't make any differences if switching the order of channels lists. However, it seems to me that the model only reads the first channel while making the inference.  Another hint indicating that the model only reads the first channel is that by looking at the log information, it prints that only 1st channel has been loaded.  

Segmenting subject with index #1 ~~~~~~~~~~~~~~~~~~~~
Loading subject with 1st channel at:

In addition, the number of input channel is defined correctly in the modelConfig.cfg.
numberOfInputChannels = 2

Could you please take a look if my understanding is correct or not, and if so, how to solve this issue and which part of code needs to be revised? Thank you very much for your time!

Best regards,
Alice

**Comment by Kamnitsask** [comment]
Hello Alice,

When a net takes multi-channel input, it takes them in a particular order. E.g. if at training you provide T1/T2, in the input layer it will learn a set of filters for T1, and another for T2. If at testing you switch the order you provide them, T2/T1, the network is still the same, and thus it applies the filters it previously learnt for T1 on the T2, and the ones learnt for T2 to T1. So it is absolutely expected that its behaviour changes (and breaks down). So, no. The same order that you use for training you should be 100% certain you give the same order at testing.

The fact that you see in the logs only info about loading 1 modality per patient, is because I wanted to indicate which case is being loaded, but not fill the logs with multiple lines per patient, so not report in the logs the loading of each single modality per case, just the 1st one.

If you want a proof for yourself, train one in T1/T2, test with T1/T2, and then in another experiment corrupt yourself the T2 (eg apply noise). You ll see that the model breaks, indicating that it uses all images.

Behaviour is as expected. Will close issue.

**Comment by alicebeauti** [comment]
Hi Konstantinos,
Thank you for your explanation which really helped me to understand the structure better.
