### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by pyaf** [Kamnitsask/deepmedic#131]
I would love to format the code according to the PEP8 style guidelines, as I can see about there are about 33 files in the repository which are not accordance to PEP8 style guidelines.
Let me know if I can open a PR for this.

**Comment by Kamnitsask** [comment]
Hello!

Definitely the style of the code needs a repass in various places. I tend to do it gradually, piece by piece in each iteration.

Please, if it's not much work for you to change those 33 lines, please go ahead and submit a PR! I ll have a look asap.

Thanks!
Kostas

**Comment by pyaf** [comment]
Hi Kostas,

It's 33 files that need to be formatted (not 33 lines). There are many tools which can format the code to PEP8 style; I'll be using [autopep8](https://pypi.org/project/autopep8/). I've used it before, and it works well. You can read about it [here](https://stackoverflow.com/a/14328499/6300703). Let me know your thoughts.

**Comment by Kamnitsask** [comment]
Oh I see, sorry, I misunderstood. Yeap, this means changes to all files basically. Hm, I have not used the tool before so I cannot judge what the outcome would be.

Two options I could suggest:
- If it's not much work for you, feel free to try it and submit a PR. I could later go over it we discuss how things look, what needs correction etc. Possibly this would be best to be done in a new branch, in case bugs are introduced (a quick skimread through questions/blogs about the tool showed that some problems can slip through.
- If this would mean work for you, that you wouldnt want to be wasted or bother with it further, then the other option is to leave it for now, and allow me some time to check the tool myself so that I get what kind of changes to expect. And then I come back to you?

Kind regards,
K

**Comment by pyaf** [comment]
Hi Kostas,

I would like to go with the first suggestion. Let me go through it, I'll get back to you on this.
