### ISSUE TITLE
Using deepmedic with other images

### ISSUE THREAD

**Issue by abderhasan** [Kamnitsask/deepmedic#136]
Hello,

I know deepmedic was designed to work with brain images. Would it be appropriate to work with other tyoes of medical images (i.e. lung)?

Thanks.

**Comment by Kamnitsask** [comment]
Hello and thank you for your interest.

Yes, the method is made to be rather generic. Users have applied for a wide variety of problems, including organs outside the brain (heart/liver/lung/abdominal/bones etc etc). It should be very good for lungs.

Here is a publication where we have applied it for multi-organ segmentation 2 years ago out of the box:
Lavdas et al, Fully automatic, multiorgan segmentation in normal whole body magnetic resonance imaging (MRI), using classification forests (CFs), convolutional neural networks (CNNs), and a multi‐atlas (MA) approach, Journal of Medical Physics

https://aapm.onlinelibrary.wiley.com/doi/full/10.1002/mp.12492

K

**Comment by abderhasan** [comment]
Thanks a lot for your kind support, appreciate it!

**Comment by Kamnitsask** [comment]
Only interesting advice I can give is, I if you apply it for images that contain whole body, what I tend to do is, first, make a mask that does not contain the air (around the body). And provide it to deepmedic as roi-mask (in trainConfig). So that training is not wasted on samples from the air constantly.

This can be done easily eg by thresholding the air and filling the wholes. (cant remember if the mask changes performance much, but I always make one when I can).

K
