### ISSUE TITLE
The correct settings for ISLES2015_SISS  Dataset

### ISSUE THREAD

**Issue by ZeinabSalkhorde** [Kamnitsask/deepmedic#140]
Hi Konstantinos,
thanks for your work and support! 
1- You reported the results of the evaluation of training_ ISLES 2015 data with Deepmedic in your article but for the testing_ISLES 2015 data, you only reported  dice measure for ensemble model  not for Deepmedic. Have a specific reason for this? How much is your result of DeepMedic evaluation for testing_ISLES 2015 data? 

2- You mentioned in your paper that the three most similar networks to build the ensemble model for ISLES 2015, What is the difference between these three networks? Is the number of kernels, number of  FMs layers, and other parameters  same in all three networks?

3- Is the number of ّFMs of each layer in the Deepmedic model for ISLES 2015 as follows?
numberFMsPerLayerNormal = [40, 40, 40, 40, 40, 40, 80, 80]
numberFMsPerLayerSubsampled = [15, 15, 15, 15, 15, 15, 30, 30]

4-You mentioned in your paper that the"Network configuration and training for ISLES 2015 data: The main difference with the configuration used for TBI and tumors as employed above is the relatively smaller number of FMs in the low-resolution pathway" but You mentioned in https://github.com/Kamnitsask/deepmedic  that the "In examples/configFiles/deepMedicOriginal/ we provide the configuration of the network as employed in our work in [1], and very similar to the model employed in our winning contribution for the ISLES 2015 challenge [2]". Which setting  examples/configFiles/deepMedicOriginal/  or examples/configFiles/deepMedic/  for  ISLES 2015 to use  ?
thanks a lot and best regards
Zeinab Salkhorde

**Comment by Kamnitsask** [comment]
Hello Zeinab, I hope you are well and thank you for your interest in our work.

1. Back in 2015 when that worked was done, the system was evaluated on the "testing phase" of the challenge. Only one submission was allowed to the participants. We submitted an ensemble of networks, the best we could train, and we also refined the predictions with a 3D fully connected CRF. See paper. A single model was never evaluated, because no multiple submissions were allowed. The platform opened up publicly much later, and we never checked a single model. I would expect that good single models should be achieving roughly ~54%, with the ensemble adding +2-3%, and the 3D CRF another ~2-3% percent (this is according to observations in the cross validation on training).

2. There were various small differences in the optimization (sgd+mom vs rmsprop, initialization, lr schedule etc) because I was developing different optimizers & lr schedules back then. But I dont think they made much difference (I m still experimenting with different ones). There are way too many factors that add variance in the ensemble anyway (which is good, you want varying good quality models in an ensemble). If you want my advice, just add as many models as you can/have, with small differences (I often make them a little bit different in the number of channels too for variation), and you should get a nicely behaving ensemble. Ensembling is especially helpful when each individual is overfitting (each in a different way, see theory of trees + Random Forests).

3. This is right. When I make an ensemble I often make some models a bit larger than others (eg +10 channels more at each layer) for variety. But I think in 2015 all models were of this size.

4. The deepMedicOriginal is as close as it gets to the one in the paper, where for ISLES15 the number of FMs in the above point (3), as shown in our short paper for ISLES. This is an evolving project, where I continuously update the default configuration with anything that seems to be overall well behaving across all databases and tasks that I experiment with, for an overall well behaving model. And this continuously updated config is deepMedic (not deepMedicOriginal). The backend is continuously changing and will continue to change as we move forward (note even the large change from theano to tensorflow).

For any further discussions around the papers, I would kindly ask them to be done via email. I would like to keep the issue tracker for technical issues such as bugs/features/etc. It helps supporting this ongoing project.

I hope the above helps!

Kind regards,
Kostas
