### ISSUE TITLE
Values of Tensors for further use

### ISSUE THREAD

**Issue by samieti02** [Kamnitsask/deepmedic#144]
Hello dear Sir,

in the  ops.py you have differents tensor like outputTrain, outputVal, ...
How can I achieve to extract the values of these tensors (or blocks [r,c,z] or [y,x,z] e.g. [3,1, 38,38,38],  [3,1, 36,36,36], ... ) and save it as nifti (or plot3D it)?
Can you please give us some tipps?

Thanks

**Comment by Kamnitsask** [comment]
Hello,

If I understand correctly, this functionality is similar to saving the feature maps.

The project has functionality built in for saving the featuremaps.
Have a look at the "Feature Maps"  section of testConfig.cfg and the corresponding parameters.
The important functions for this are in /deepmedic/routines/testing.py , where the testing function returns feature maps along with the probability maps.
In the cnn3d.py, you can find the feature-maps/tensors that are setup as the feeds that the testing routine calls for testing, if you look for the function
setup_ops_n_feeds_to_test(..)

I hope the above helps.
K

**Comment by samieti02** [comment]
Hello dear Sir,

when you convolve the input with the filter, you have an output.
If you have for example
SegDimTrain [40,40,40], and KernelDim [ [3,3,3], [3,3,3], [3,3,3] ]
You will have as outputTrain [3, 1, 38, 38, 38 ], where (38, 38, 38),  can be interpreted as (r,c,z) or (x,y,z)
How can i extract the [38,38,38] and save it as numpy array? 
i have tried:

sess = tf.Session()
with sess.as_default():
       newArr =outputrain.eval()

Also tried
sess = tf.InteractiveSession()
newArr =outputrain.eval()

in ops.py after outputTrain = tf.transpose( outputOfConvTrain, perm=[0,4,3,2,1] )
but always got an error

Is there a better way to achieve that?

Thanks

**Comment by samieti02** [comment]
dear Sir,
can you help me understand some variables in the code?

You have this one "fmsReturnedForATestBatchForCertainLayer"
The FM that are contained in the variable above, are for the images used for training or for testing?
I would say training, because, FM are used to help one, to build a network. We use them, most of the time for the visualization. I am not quite sure about my answer, because you added Test in the name of the variable.
If my answer is not correct, how can we get the FMForTraining?

When we convolve the input and the output, we have something like 
input_channel * filter => 
(Train) [5,1,40,40,40] * [4,1,3,3,3] := [5,4,38,38,38]
(Test) [3,1,40,40,40] * [4,1,3,3,3] := [3,4,38,38,38]
Which variables in the code contain the results of the convolution and how can we save them as array?

I saw also the comment 
# Input signal given in shape [BatchSize, Channels, R, C, Z]
And through compilation I had in "channsOfSegmentsForSubepPerPathwayTrain" [500,4,38,38,38]
Channels are the number of FM => if we have 4 filter, we will have 4 FM, for each layer
It is also not clear for me 
[500,4,38,38,38] will mean, that there are 500 segments, and how to interpret the rest [4,38,38,38]?

Thanks

**Comment by samieti02** [comment]
ConvolutionFlow of deepmedic

Lets say you have 
input size = [240,240,155] for R,C,Z or H,W,D or X,Y,Z
SegmentsDimTrain = [40,40,40]
kernelDimPerLayerNormal = [[3,3,3],[3,3,3],[3,3,3]]
We convolve, first the range [0:39 , 0:39, 0:39] of the input size with the filter
( With stride +40 , that means for the next convolution, we will have the range [0:39 , 40:79, 0:39]  )
we will have for the R,C   240/40 = 6  , in both dimensions 6x6=36 and with Z 155/40~3,8~4 , a total of 6x6x~4=144 segments

batchSizeTrain = 5 
numberTrainingSegmentsLoadedOnGpuPerSubep = 500
We have 144 segments and we set '500' , the algortihm will run till 144.
What is the relation between numberTrainingSegmentsLoadedOnGpuPerSubep , NumOfSegmentsOnGpu , and batchsize ?
If 144 segments are NumOfSegmentsOnGpu , it means that a batch will contain the first 29 (144/5) segments, in this case for the first batch we have  for Z [0:39] , the 1st row, 2nd row, 3rd, 4th and 5th row  with the first 3 segments,
And then we have the next batch, that will continue from the 5th row 4th segment, and so on ?

**Comment by samieti02** [comment]
With a dataset of 1000 examples. We can divide it into batches of 200, then we will need 5 iterations to complete 1 epoch.

Regarding the above example
If we set numberOfEpochs = 4, with batchSizeTrain = 5, we will have for 1 epoch , 4 batches of 29 segments and 1 batch of 28 segments?

And if we want to reconstruct an image, we can take th result of the convolution of the input with the filter, That means the first [B, C, 38,38,38] = [B,C,0:39, 0:39, 0:39] , then [B,C,0:39, 40:79, 0:39] , then [B,C,0:39, 80:119, 0:39], then [B,C,0:39, 120:159, 0:39]
And we can concatenate all the segments resulting of the convolution to have an image 

Does the idea  of reconstructing an image make sense?
I f yes , which variables in the code, contain [B, C, 38,38,38], [B, C, 3&,368,36]?

**Comment by samieti02** [comment]
Hello dear Sir,
we are still waiting from answers. This will help all of us.
Thanks!

**Comment by Kamnitsask** [comment]
Hi,

Regarding you main question, how to get the output of the convolution out:
As I previously said in my answer, there is already built-in functionality for this. When you do "visualisation of FMs" with DeepMedic, what you get is exactly what you want. The output of the convolutions at each layer. So, please look into that functionality. Using it out of the box will give you the output of the convs.

The only thing noteworth is that you will get it for the whole image, as a nii. Not for patches. DeepMedic internally (in the ./routines/testing.py) breaks down an image in segments. It processes each one-by-one, gets the output of convs for one-by-one, and stitches all of them back into one nii of the size of the input volume.

To do this for your training images instead of your testing images, simply use the testing routine, but give the training images as input. Simply do this with a pre-trained network (-load /path/to/pretrained). That's all.

If you want to do this patch-wise, you will need to find your way around yourself. This requires good familiarity with Tensorflow and patience. Something like the  outputrain.eval( *INPUT* ) that you mentioned above, but there it didnt work because you didnt give an input. It is impossible for me to provide you with detailed guidance for this, and this issue tracker is not the appropriate place for this. I believe the built-in functionality should be sufficient for what you need.

Regarding the rest of the questions, I am sorry, but I cannot drift into details about how the code works here, nor is the issue tracker a place for this. I honestly would love to, I *really* don't want to be rude, but it's impossible time-wise, and I have to prioritize issues that have to do with problems/maintenance/extensions of the project.

I will close this issue because the functionality for the main issue is already in place (visualising FMs).

Kind regards,
Kostas

**Comment by samieti02** [comment]
Hello,
thanks for the tips

> To do this for your training images instead of your testing images, simply use the testing routine, but give the training images as input. Simply do this with a pre-trained network (-load /path/to/pretrained). That's all.

Regarding the quote above, i changed the paths in these differents files: testChannels_flair.cfg, testChannels_t1c.cfg, testGtLabels.cfg, testRoiMasks.cfg
like
`../../../dataForExamples/brats2015TrainingData/test/brats_2013_pat0001_1/Flair_subtrMeanDivStd.nii.gz
`
in
`../../../dataForExamples/brats2015TrainingData/train/brats_2013_pat0005_1/Flair_subtrMeanDivStd.nii.gz
`

and use the command

```
./deepMedicRun -model ./examples/configFiles/deepMedic/model/modelConfig.cfg \
               -train ./examples/configFiles/deepMedic/train/trainConfig.cfg \
               -load ./examples/output/saved_models/trainSessionDm/deepMedic.trainSessionDm.final.2019-01-12.14.04.32.2542195.model.ckpt \
               -dev cuda0
```

Thanks
Sir

**Comment by Kamnitsask** [comment]
Hello,

Have you had a look in the testConfig.cfg, at the end, under the section marked as "++Feature Maps++" ? You ll need to uncomment those.

**Comment by samieti02** [comment]
yes Sir after i made the steps above, i set the values of minMaxIndicesOfFmsToSaveFromEachLayerOfNormalPathway like this

minMaxIndicesOfFmsToSaveFromEachLayerOfNormalPathway = [[0,4],[0,4],[0,4]]

and i got in the folder features of test , the FM of the training images (i suppose)

**Comment by Kamnitsask** [comment]
Thank you. The above must have then returned features maps 0-to-4 for each of the 3 first layers of the normal-resolution pathway.

I hope this serves you well.

Thanks
