### ISSUE TITLE
Preprocessing: Bias field correction in ROBEX

### ISSUE THREAD

**Issue by satrajitgithub** [Kamnitsask/deepmedic#148]
Hi @Kamnitsask 

In the Deepmedic paper, I came across two things:
- "Brain masks were obtained using the ROBEX tool ( Iglesias et al., 2011 )."
- "No bias field correction was used as preliminary results showed that this can negatively affect lesion appearance. "

Now while using ROBEX, I noticed that it has an intrinsic bias field correction step. When you used ROBEX for preprocessing, did you omit this step?

Thanks in advance!

**Comment by Kamnitsask** [comment]
Hello, sorry for late reply, the further I get in the PhD the less time I manage to find for my own research apparently... Sorry.

Bias field is used in ROBEX indeed. Since the analysis of the paper mostly focuses on the CNN, what I meant was not using bias correction on the input that the CNN sees.

Thanks!
K

**Comment by satrajitgithub** [comment]
Thanks Kostas. Just wanted to make sure if you modified the brain extraction code to remove the bias field correction portion from it.

**Comment by Alexfengbowen** [comment]
Hello, when I used the new data set for training, it was required to create a ROImasks through ROBEX, but I did not understand how I should use ROBEX, could you please instruct me on the detailed steps?
