### ISSUE TITLE
Comments on the README.md

### ISSUE THREAD

**Issue by josephwinston** [Kamnitsask/deepmedic#15]
Some notes that might help others.  

The format of the model file is described in the documentation as ```examples/output/cnnModels/tinyCnn.initial.DATE+TIME.save```.  Note that this might mean a space in the name as shown here: ```examples\output\cnnModels\tinyCnn.initial.2016-08-31 08.00.26.271000.save```  The space in the file name means that you must either quote the name for example ```"examples/output/cnnModels/tinyCnn.initial.2016-08-31 08.00.26.271000.save"``` or  escape the space like this

 ```examples/output/cnnModels/tinyCnn.initial.2016-08-31\ 08.00.26.271000.save```

The markdown for plotting the training progress is wrong as well as the command lines the program accepts.  The revision eba26d7 reports the following options are valid:

```bash
usage: plotTrainingProgress [-h] [-d]
                            [-c CLASSES_TO_PLOT [CLASSES_TO_PLOT ...]]
                            [-m MOVING_AVERAGE] [-s]
                            log_files [log_files ...]
```

**Comment by Kamnitsask** [comment]
Sorry for the very late reply. Been quite busy with another project lately, sorry.

First issue I had noticed, but fixed by changing the format of the name of the files when saving. Now has no spaces, but a dot instead, so that it's more windows-friendly.

You are right about the second issue, there was indeed a small inconsistency in the markdown. Correcting it now for the next commit.

Thanks a lot for the feedback. And once again, sorry for the late reply.

Kostas
