### ISSUE TITLE
Printing Model Memory requirements

### ISSUE THREAD

**Issue by Geeks-Sid** [Kamnitsask/deepmedic#151]
Hi, 
Can we print the memory requirements of the model given the varying batch size of the varying structure of the model? This could be a great feature to add to optimally use GPU at 100% and also help in deployment testing.
If not, can I get help in calculating the memory requirements of the given model?

Thanks

**Comment by Kamnitsask** [comment]
This is potentially far more difficult than it may look. Memory requirements come from different aspects of the model.

It is easy to compute the memory required for your data, for the feature maps, and for the parameters of the model. You can find help about this on multiple books/papers, easy to compute.

But there are memory requirements dependent on the underlying implementation, which is very difficult to derive except if monitored in runtime. For example, different implementations of the convolution can have drastically different memory requirements. I have not looked into whether Tensorflow provides functionality for computing such things, but I have not noticed any. I guess your best bet is to configure tensorflow acquire memory dynamically (instead of all available at start) and then just monitor usage at runtime.

Kind regards,
Kostas
