### ISSUE TITLE
SPECT image adaptation

### ISSUE THREAD

**Issue by atilaorhon** [Kamnitsask/deepmedic#21]
First of all, thank you for open-sourcing for your code on GitHub. I am currently working on a big dataset (>20,000) of SPECT images. I will be doing 'TBI/PTSD/Comorbidity/Healthy' classification using 3D CNN architectures and found your papers really helpful. I would like to ask you some follow up questions regarding using your code for early prototyping, if I may:

1- SPECT images are 128x128x27. Is this dimensionality too large to be processed? Would  downsampling it directly or using the original resolution + downsampled patches in a multi-channel architecture be feasible?

2- You also mentioned that the 3D images need to be NxNxN. If I modify the model for a NxNxM input and make further modifications to feature map and kernel sizes, would there be any further problems to consider?

3- You also mentioned that there is no need for inter-subject image registration. I was advised to co-register the whole dataset. What was your motivation behind advising against inter-patient image registration? 

Note: My dataset comes from a single clinic and they claim meticulous data collection procedures with extra emphasis on inter-subject data compatibility.

4- I have 128 ROIs. How effective is 'Normalization within ROIs' as opposed to 'Global Normalization'? Is performance contingent upon ROI based normalization?

5- I am also switching from segmentation to classification so I plan to use Multi-Channel 3D CNNs for feature extraction with a cascaded SVM for  classification. Would recommend some other cascade or just a final layer of Fully Connected Perceptrons?

**Comment by Kamnitsask** [comment]
Hello,

Thanks for your interest in my work atilaorhon, hope you find it useful.

1) I do not consider an 128x128x27 volume particularly large. This is smaller than the cases where I have applied it, so dont hesitate, go on and work with the original resolution as it is.

2) Where did I mention that about same dimensions at every axis? If I have somewhere, let me know where cause it needs correction. It does not have to. 128x128x27 is fine. I highly advise for them to be resampled to the same voxel size in all axis though (eg 1x1x1mm voxelsize) cause the default configuration has a cubic 17^3 receptive field. Of course, if eg you have larger voxelsize in the 3rd dimension, you can change the filters to make them smaller in the 3rd dimension. Although these are probably task-specific choices.

3) The algorithm does not "require" registration. I do not advice against it, just state it is not required, since the code is released as a tool for generic, task-independent, segmentation. If you believe registration would "simplify" a task for the network, then please go ahead. I personally often do it as well. (merely by intuition, never tested it, but I believe in most brain lesion tasks registration should be beneficial or at least not harmful)

4) What do you mean 128 ROIs? With ROI you mean labels/classes perhaps? When I say ROI, I mean the area of the image that you wish the network to be applied on. Eg, in the case of Brain MRI, the brain-mask (so that you dont waste training time and capacity on training samples from the air, or waste time segmenting it in test time).

It is sensitive in correct normalization. The default configuration was set for normalized data by subtracting the within-roi-mean and dividing by within-roi-std (see other issue).

5) If I understand correctly, you mean classifying the whole image, eg (good/bad outcome). In that case you ll need to do some downsampling there cause of GPU memory issues (either prior, or in the network with pooling). FYI my code currently does not elegantly support pooling. Building a standard Classification CNN is perfectly fine for your task. Also, Random Forests work wonderfully on the CNN-extracted features. 

Kostas

**Comment by Kamnitsask** [comment]
Considered closed for now.

Kostas
