### ISSUE TITLE
Model variables initialization 

### ISSUE THREAD

**Issue by sahar90o** [Kamnitsask/deepmedic#221]
Hello, 
I am using DeepMedic for Brain metastases segmentation. I want to train several DeepMedic models with different initialized parameters. Could you please guide me? 
As far as I checked in trainSession.py at line 194 the network and trainer variables are initialized. However I could not find any random seed variable for initializing. How should I do that? 
Thank you in advance for your help. 

Bests, 
Sahar

**Comment by Kamnitsask** [comment]
Hello Sahar,

Thanks a lot for your interest in trying the project for your data, and for double-checking about your question.

Indeed, we do not set a specific random seed anywhere in the code.
If you run the training session twice, the model will be initialized each time, but with a different random seed. (in fact, originally, we did not set the seed in the code, to have exactly this behaviour, so that we avoid results dependent on seed)

You can achieve what you want (train multiple models with different initialized params) simply by running the same training process, multiple times.
What I tend to do, to keep separate logs / folders / etc separate and clean for each of these experiments:
Lets say you want to run 3 experiments, with the same model, the same training config, just different seeds...
- Have 1 model-config file (common for all 3 expers)
- Have 1 train-config file, but copy paste the exactly same file 3 times. Say... train_config_1.cfg , train_config_2.cfg train_config_3.cfg
- In each of these 3 copies, open the file with a text editor and just change the "sessionName = "trainSessionDm" " line. This sets the "name" of each experiment, that is used to name the output folder, the models, the log, etc. So, just give 3 different names. E.g. sessionName = "experiment_seed_1", sessionName = "experiment_seed_2", sessionName = "experiment_seed_3" in the 3 training-config files. Leave the rest of the file exactly the same between the 3 copies.
- Then, just run 3 training sessions (experiments), with the same command, but pointing to a different train_config (so that you get 3 different output folders, one per seed. E.g.:
python ./deepMedicRun -model .../path/to/modelConfig.cfg -train ./path/to/train_config_1.cfg -dev cuda0
python ./deepMedicRun -model .../path/to/modelConfig.cfg -train ./path/to/train_config_2.cfg -dev cuda1
python ./deepMedicRun -model .../path/to/modelConfig.cfg -train ./path/to/train_config_3.cfg -dev cuda2

Makes sense?

**Comment by sahar90o** [comment]
Dear Konstantinos, 

Thank you very much for your prompt and complete response. 
Yes, it makes sense, thank you :)

**Comment by sahar90o** [comment]
I just have another question regarding intensity normalization. 
For your network is it better to apply zscore normalization on whole MRI scan (including background and foreground) or anly apply it to the brain region?
Thank you.

**Comment by Kamnitsask** [comment]
Hi Sahar,

I normalise the whole image BUT with means/stdev of the pixels that are within the brainmask.
i.e.
Compute brainmask
Compute mean and std of pixels under brainmask
Then for every pixel of the image (not just brain) do: pixel' = (pixel - mean_brain) / std_brain

Note: the above is done separately per modality (if e.g. you work with MRIs).

I hope this clarifies it.

I will now close the issue as the original issue has been answered. Feel free to raise another one for another question (just so that issue title = issue answered)

Thank you!
