### ISSUE TITLE
Feature Maps settings are commented out of provided example configs

### ISSUE THREAD

**Issue by csestili** [Kamnitsask/deepmedic#23]
We noticed that feature maps were not being generated during testing, and we weren't sure why, because our settings for the feature maps in the testing config file appeared to be correct.

The provided testing config file has the feature maps section commented out with triple quotes, and we are using modified copies of the example config files, so our settings were not being used. This isn't actually a bug, and it would have been obvious if our text editor correctly highlighted multi-line comments, but I wanted to post this as an issue in case anyone else is wondering why their settings aren't being used.

There are also sections of the provided model and training config files that are commented out, which would lead to similar problems.

**Comment by Kamnitsask** [comment]
Indeed, thanks Carol. 

This is commented out by default because I did not want to save FMs by default, since they are many and would occupy loads of space. So I commented out, and hoped that it ll be intuitive to users how to uncomment it and use it if needed.

Sorry for the inconvenience. It's kind of difficult for me to come up with a easy-to-use and clean default configuration, while allowing the use of quite some meta-parameters/functionality that is available, when needed. I ll try to make things clearer in the future.

Once again, thanks for the feedback.

Kostas
