### ISSUE TITLE
Testing process kills itself

### ISSUE THREAD

**Issue by csestili** [Kamnitsask/deepmedic#29]
Hello,

While running testing on a large model with large kernels, it seems like the testing process kills itself with no explanation why:

```
###########################################################################################################
############################# Starting full Segmentation of Testing subjects ##########################
###########################################################################################################
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~ Segmenting subject with index #0 ~~~~~~~~~~~~~~~~~~~~
Loading subject with 1st channel at:[...]/niis_input/fa1_channel.nii
/data/HDFT/pkg/deepmedic-master/deepmedic/trainValidateTestVisualiseParallel.py:151: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if allChannelsOfPatientInNpArray == None :
Starting to (tile) extract Segments from the images of the subject for Segmentation...
/data/HDFT/pkg/deepmedic-master/deepmedic/trainValidateTestVisualiseParallel.py:566: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if channelsOfSubsampledImageNpArray <> "placeholderNothing" :
Killed
```

This testing subject has been segmented without error on previous, smaller models, so I think that the input channel and ground truth niftis are fine. I'm also pretty sure that I've seen these FutureWarnings on previous successful testing rounds.

Any ideas what could be happening?

**Comment by Kamnitsask** [comment]
Hello csestil,

I believe this is from the log file? Could you run this testing once again and copy paste here the error message that you ll see on the terminal?

K

**Comment by csestili** [comment]
Hi Konstantinos,

This message is actually from the terminal, not the log file. The log file does not contain the FutureWarnings or the "Killed" message.

I am running other training right now, but I can post the full message from the terminal when the training is done and the GPUs are available.

I will also send you the testing log file now.

Thank you for your help!

**Comment by Kamnitsask** [comment]
This problem was due to running out of memory (RAM, not GPU) at testing.

This was due to inefficient design of the testing process, coupled with the user having defined small size of input segments, same size as the receptive field. At the begining of the testing process, the image is first tiled to multiple segments, as many as needed in order to segment it all. A small segment size leads to more segments being required for the tiling. All of them used to be loaded in RAM at the same time, and then gradually load them on GPU for inference. In this case, numerous largely overlapping segments loaded in RAM at the same time led to out-of-RAM error.

Fixed in branch testingRefactored1, now merged to master. The testing-segments are gradually extracted, batch-by-batch, instead of all at once.

Closing.
