### ISSUE TITLE
Indentation problem

### ISSUE THREAD

**Issue by viridyu** [Kamnitsask/deepmedic#36]
Hi,

I tried to add some lines in the codes. However, I found the rule of indentation in these codes was not same with the one I used to following. I usually align the lines with same space like four space, but in these codes, It would be different between the lines in the same 'def'. 

Does anyone have the same problem? Could you help to tell me what's the indentation rule of these codes? Thank you.

**Comment by Kamnitsask** [comment]
Hello viridyu,

This is one of the biggest mistakes I have done, result of using two different IDEs for development and not paying attention to this issue for a long time.

Indentation includes both spaces and tab characters. To view the code correctly in an IDE, set the tab to correspond to 8 spaces. Sometimes the inner code block/loop is inner by 4 spaces, sometimes by tab. When you insert new code, just carefully go with what is already there for now.

I have corrected this issue in an unpushed version, but that piece of code needs further validation, and it will take a few weeks I believe because it's together with a bunch of other stuff :-/

Let me know if you still have problems with this.

(Please leave this issue open. I badly need to fix this asap)

Sorry for the inconvenience, this mistake should have been avoided long time ago...

K

**Comment by viridyu** [comment]
Hi @Kamnitsask ,

Thank you for your reply. Hope you finish it soon.

**Comment by Kamnitsask** [comment]
Issue fixed in branch "identation" and will be merged in master soon. Indentation is fixed to be consistently 4 spaces everywhere. (no \t tab characters nor varying 4/8 spaces indentation anymore).

Sorry for the inconvenience. Should have fixed this long time ago.

K

**Comment by viridyu** [comment]
@Kamnitsask Thank you so much.

**Comment by Kamnitsask** [comment]
@viridyu No, thank you for the feedback, appreciated.

Opening issue till I merge to master.

K

**Comment by Kamnitsask** [comment]
Merged fixes from branch "identation" to master. Commit 72ca3c1.

Indentation should be consitent everywhere, 4 spaces. No tab characters.

Once again, sorry for the inconvenience and thanks for the feedback.

Closing issue.
K
