### ISSUE TITLE
cnmem problem

### ISSUE THREAD

**Issue by viridyu** [Kamnitsask/deepmedic#41]
When I run the main code as 'THEANO_FLAGS='floatX=float32, device=gpu0, lib.cnmem=0.9' python ./deepMedicRun -dev gpu -train ./examples/configFiles/deepMedic/train/trainConfig.cfg -model ./examples/output/cnnModels/deepMedic.2016-12-19.06.56.35.928714.save '
It gets 'Using gpu device 0: Tesla K40c (CNMeM is disabled, cuDNN 5005)'.
However, when I used it several weeks ago, it worked very well. I just updated the codes to the newest one. Besides, there is no any problem with cnmem in my server.  

Could you help me with it?

Thank you

**Comment by Kamnitsask** [comment]
Hello viridyu,

I am setting the THEANO_FLAGS internally in ./deepMedicRun. So whatever you pass in the command line is overwritten. I will try to give a better API for this, but made it like this so that users that really have no clue of Theano can still go with good "default" settings given by me.

To change the lib.cnmem, open ./deepMedicRun, look for the line with "THEANO_FLAGS", and add it at the end of that line. 

Let me know if this works.

K

**Comment by viridyu** [comment]
Thank you so much @Kamnitsask . It works well now.
