### ISSUE TITLE
fine-tune pre-trained model / freeze layers

### ISSUE THREAD

**Issue by viridyu** [Kamnitsask/deepmedic#42]
Hi,

Can I use the pre-trained models by deepmedic and freeze some layers to do fine-tuning? If so, could anyone tell me how to change the configuration of it? Thank you so much.

**Comment by Kamnitsask** [comment]
Hi viridyu,

I think I had implemented an easy way to do it, but never exposed it because it was not made very "intuitive" if I remember correctly. I ll look at the state of this in the next couple of days and update you. Perhaps it's a good time for me to finish that functionality.

(If you are in a very significant hurry for this functionality, let me know so that I don't keep you waiting much.)

K

**Comment by viridyu** [comment]
Hi @Kamnitsask ,

I am really in a hurry for it. Could you tell me the easy way? Thank you so much.

**Comment by Kamnitsask** [comment]
Hello again,

Everything required for fine-tuning a pre-trained model is now on the new branch "freezeLayers". To be merged to master soon. The documentation is updated in section 3.2, so look there, it has everything you need in order to pre-train + fine-tune I believe. Never fine-tuned myself, so I can't provide a suitable learning-rate schedule. You ll have to play a bit with that one perhaps.

Freezing layer: I do not know why you would wish to freeze layers. When fine-tuning, I believe it would be better to fine-tune all of them for the specific task. But still, functionality for freezing now provided.

ps1 to @viridyu : An important thing is that branch "freezeLayers" is branched from the "rebaseMultiscale" branch. Everything should work the same as on the master-branch if you just use the same config files that you used before.  BUT you need to change something small. You need to move the "Regularization L1 and L2" and "Optimization" parts of the "modelConfig.cfg" file to the "trainingConfig.cfg" file. Just cut+paste. Compare the version of these files as they are on master and on the new branch and you ll easily spot the sections that were moved.

ps2 to @viridyu : The new branch is not backwards compatible. You'd need to train a new model using that branch, and then fine-tune. Changes are validated and soon to be merged to master.  If you reeeeaaaally don't want to retrain for some close deadline, email me at konstantinos.kamnitsas12@ic.ac.uk (though know I ll be unavailable for a couple of days).

Hope this helps. Thanks for the interest and feedback.

Kostas

**Comment by viridyu** [comment]
Hi @Kamnitsask , I haven't seen the updated documentation in section 3.2, have you uploaded it?

**Comment by viridyu** [comment]
Thank you so much, @Kamnitsask . Hope you update the branch suitable for the pre-trained model soon. Thank you again.

**Comment by Kamnitsask** [comment]
I m not sure if I was clear above, so let me clarify (mostly for any future user that looks at this issue):

The "freezeLayers" branch now provides the functionality needed for someone to be able to train a model (like before) and then easily fine-tune it with a second training session on another database (see documentation, Sec 3.2). 

The branch also provides the option of keeping certain layers fixed/frozen, in case it's one wishes (also see Sec 3.2, and the additional variables "layersToFreeze" in trainConfig.cfg of deepMedic).

I currently do not provide already-trained models, but these changes now make it meaningful, so I might do so in the near future.

The changes will be merged to master soon.

Note: (here there might have been a confusion) The changes are still not backwards compatible. Which means, if you had a model trained by using a previous version of the code, you still cannot load/unpickle it with this new version of the code. So, you cannot fine-tune it. The fine-tuning capabilities offered with these changes are for models that are trained on database-A with this code, and then user wants to fine-tune the model on another database-B. I am slowly building towards making the saving/loading backwards compatible, but because significant changes are needed now and then in the code, it's not as easy as it sounds.

Will keep issue open till changes are merged to master.

Hope this is helpful. Once again, thanks for your interest and feedback.
Kostas

**Comment by viridyu** [comment]
@Kamnitsask , I totally understand your meaning. Thank  you so much.

**Comment by viridyu** [comment]
Hi @Kamnitsask ,  Now I have another question. If I changed the number of layers and I still want to use some layers' weights of the pre-trained old model to do fine-tuning, do I only initialize the new layer.params with the corresponding old layer.params?

**Comment by Kamnitsask** [comment]
Changes pushed to master on 26 March 2017, commit  4ef2d64.

Closing.
