### ISSUE TITLE
python code of Data Pre-Processing 

### ISSUE THREAD

**Issue by danieleewww** [Kamnitsask/deepmedic#43]
Is there a reference python code of data pre-processing for deepmedic?

**Comment by Kamnitsask** [comment]
Hello,

First of all thank you for your interest in our work.

I am sorry but I currently cannot provide scripts for this. The reason is that data can be really heterogeneous in their properties and making a collection of scripts that would *guarantee* appropriate pre-processing for all cases are not trivial to make. I believe such scripts could really introduce errors in a pipeline for data/cases that are different from what I can think of. For this reason, I prefer leaving this process to the users, who are more knowledgeable about their own data and how to process them more appropriately.

What is required/advised for my software is described in Sec. 1.3 and 4.

Kind regards,
Kostas

**Comment by Kamnitsask** [comment]
Closing
