### ISSUE TITLE
weight-maps / weighted images

### ISSUE THREAD

**Issue by viridyu** [Kamnitsask/deepmedic#50]
Hi, Does anyone know how to get the weighted-maps of brain tumor images for extracting samples? Thank  you.

**Comment by Kamnitsask** [comment]
Hello viridyu,

I believe you are refering to the weight maps that are mentioned in:
- the [trainConfig.cfg](https://github.com/Kamnitsask/deepmedic/blob/master/examples/configFiles/deepMedic/train/trainConfig.cfg) of deepMedic, such as at the variable "weightedMapsForSamplingEachCategoryTrain"
- the weightMapsBackground.cfg / weightMapsForeground.cfg in the same folder

They provide just another option to perform the sampling of the training samples. In default configuration they are not used. You can notice that in the trainConfig.cfg of deepmedic, this variable is commented out. Also note that the variables of this whole section "advanced sampling" are basically not used when "useDefaultTrainingSamplingFromGtAndRoi=True" as noted there. So, if you just want to try the default configuration, just disregard them. You can even delete the files if they confuse you.

In case you or anyone else is interested, these weight maps can be used to point out where to "focus" more the sampling of each class. Eg, if class 1 are lesions, and you identify (yourself, after experimentation) that the segmentation tends to do more mistakes in the front of the head than in the back, you can engineer (yourself) some maps with a greater weight in the lesions at the front of the head than at the back, so that you sample them more frequently, so that you learn them better.

The above being said, I understand I havent provided documentation for this functionality yet, so feel free to disregard it. I am planning to extend the documentation a bit in the next push (hopefully this weekend. Validation experiments are done.). I will explain more about them there hopefully.

For now, I guess you can just disregard them :)

K

**Comment by viridyu** [comment]
Thank you so much for your detailed description, @Kamnitsask . This really helps me a lot.
