### ISSUE TITLE
Move GPU to CPU

### ISSUE THREAD

**Issue by JavierCoronel** [Kamnitsask/deepmedic#65]
Hi, I trained a model on GPU and now I'm trying to use this model in another machine (this one hasn´t GPU). Is there a way to move the model from GPU to CPU and use it for testing in the normal way?

Thanks,

Javier

**Comment by Kamnitsask** [comment]
Hello Javier,

This is one functionality that I haven't really experimented with. I never thought I d use a model on a CPU, simply because it's slow, but I understand that some users may want to, for models of certain size.

The problem is that, when Theano is run on the gpu (deepmedic with the -dev flag), the [theano.shared variables](http://deeplearning.net/software/theano/library/compile/shared.html) of the CNN that hold its parameters (weights, biases etc) take the form of CudaNdarray (automatically by theano). When the model is currently saved within the code, an instance of a CNN is pickled as is, which contains these variables, so on the disk, these variables are actually pickled as CudaNdarray objects.

If you try to load this object to test with it, without the -dev flag (to work on the CPU), theano isnt using Cuda, and tries to load these CudaNdarray objects, but will fail with a message:
raise ImportError("Cuda not found. Cannot unpickle CudaNdarray")

This is a problem of the saving mechanism, that pickles the theano.shared variables. I should have designed it to actually pickle them as numpy arrays. I hope I will change it in the future, but I am currently overwhelmed with other tasks.

If you badly want this functionality, you can probably hack it within a couple of days:
Have a look at the file:
https://github.com/Kamnitsask/deepmedic/blob/master/deepmedic/cnnTransferParameters.py
The functions there are used to transfer parameters between a pretrained and a new model. See relevant documentation, eg the [Section 2 here](https://github.com/Kamnitsask/deepmedic/blob/master/documentation/docTransferParamsResetOpt.md).

The function transferParametersBetweenLayers(myLogger, layerTarget, layerSource ) will show you all parameters that are relevant for the forward pass of a CNN. These are the ones that are normally pickled as theano.shared variables. You could make a similar  function, that after loadining the gpu-trained model of yours, takes the values of each of these variables (variableName.get_value() returns a numpy array), and pickle them as numpy arrays.

After that, you could create a brand new model with -newModel. And you then would need a second script, that would load the pickled numpy arrays (above) and would set the values of the theano.shared-parameters of the model to the values of the numpy arrays (variables.set_value(numpyArray)).

After that, you could use a -test function without a -dev option with that last model (thus running on CPU), which should now have the parameters, but not in a CudaNdarray format, so it should run on the CPU.

Sorry for the inconvenience, I know the above may not help too much and sound quite some work. As I said, I d love to improve it, but I cannot do it very soon as certain other things have higher priority, sorry.

Kind regards,
Kostas

**Comment by JavierCoronel** [comment]
Ok, got it. Thanks for your advise, I will try it and let you know.

Javier
