### ISSUE TITLE
Problem using DeepMedic on GPU (with Theano 0.9?)

### ISSUE THREAD

**Issue by luciaL** [Kamnitsask/deepmedic#69]
I use the cshell commond:
./deepMedicRun -dev gpu -newModel ./examples/configFiles/tinyCnn/model/modelConfig.cfg
Then I got a ValueError:  You are tring to use the old GPU back-end.It was moved from Theano.Use device=cuda* now.Have you meet the same error?Please help me to figure out how to solve the problem?

**Comment by Kamnitsask** [comment]
Hello,

Sorry for this. I have not encountered it. It seems it has to do with the theano version.

In the latest theano 0.9 they introduced a different backend. Most of my experiments have been done with theano 0.7 and 0.8. I think I have used 0.9 too without problems, but I will have to double-check this as soon as I find time.

See http://deeplearning.net/software/theano/tutorial/using_gpu.html
With the theano-flag device=gpu you use the old back end (pre theano 0.9), with device=cuda you use the new backend (added in theano 0.9).

Currently, the above flag is pass from the "-dev gpu" option, parsed by the file "./deepMedicRun", and passed to the theano flags in the function "setEnvironment".

What you can do to try if it works is, disable the function "./deepMedicRun -> checkDevicePassedCorrectly" and then pass to the command line "-dev cuda" instead of "-dev gpu".

Let me know how the above goes. I thought that -dev gpu should still work... I will try to find time to look into this issue further...

Please leave the issue open.

K

**Comment by luiscarm9** [comment]
This worked for me!

**Comment by stefanpsz** [comment]
@luiscarm9 Could you run stuff on the GPU using this solution? For me it worked for me in terms of being able to create a model and also training it, however this was **not** running on the gpu. I was using Theano 0.9.0 with gpuarray library and cuda 7.5/8.0 (tried both) with CuDNN v5. Depending whether I passed "-dev gpu" or "-dev cuda" I was getting either "ContextNotDefined: context name None not defined" or a segfault while compiling the training model. After trying several days trying to make it work I just found out that my only solution was to downgrade Theano to 0.8.0, use cuda 7.0 and CuDNN v4 and is working like a charm.

I might be completely wrong, but seems like the only solution is to actually change the deepMedic code if you want to run in on the new gpu back-end as suggested here:
https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Best wishes!

**Comment by Kamnitsask** [comment]
I am sorry for not getting back to this yet. I still have not managed to find time to look into the Theano-0.9 version issue... Yes, as stefanpsz said, I d suggest you downgrade to 0.8.2 if you want to try the code. I am using 0.8.2 with cudnn v5 and cuda 8 and never had a problem.

I badly need to get back to this and make sure theano 0.9 is properly integrated, but too many deadlines running at the same time >.< Sorry for this.

(ps: Hi stefan! Hope you are well dude! Thanks for the help :))

K

**Comment by tybrad11** [comment]
I'm having this same problem. Downgrading cuda and theano is not ideal as I'm using a shared resource.

**Comment by Kamnitsask** [comment]
Update on this:

I have found Theano-v0.9 to have a few problems when combined with different versions of cuDnn (issue: https://github.com/Theano/Theano/issues/5463).
The problems seem fixed in the Theano-v0.10 version (still in beta). So...

In branch "supportTheano09" I have updated the deepmedic code to be calling only the new backend. And I have updated installation instructions on how to install newest versions of dependencies properly. But upgrading straight to Theano-v0.10beta . Will push the branch to master after v0.10 is officially released.

Till then, if you want to try it, try the branch.
