### ISSUE TITLE
ValueError: could not broadcast input array from shape (34,34,34) into shape (1) at start of training

### ISSUE THREAD

**Issue by gourie** [Kamnitsask/deepmedic#70]
Hi Kostas,

I keep getting a weird ValueError at start of training that I can't explain...

`TIMING: Extracting all the Segments for next Training took time: 200.78(s)
:=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Training. :=:=:=:=:=:=:=:=:
An error has occured during the function execution
Traceback (most recent call last):
  File "/home/anaconda2/lib/python2.7/site-packages/ppworker.py", line 90, in run
    __result = __f(*__args)
  File "<string>", line 180, in getTheArraysOfImageChannelsAndLesionsToLoadToGpuForSubepoch
  File "/home/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (34,34,34) into shape (1)
Traceback (most recent call last):
  File "/home/anaconda2/bin/deepMedicRun", line 4, in <module>
    __import__('pkg_resources').run_script('deepmedic==0.6', 'deepMedicRun')
  File "/home/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/anaconda2/lib/python2.7/site-packages/deepmedic-0.6-py2.7.egg/EGG-INFO/scripts/deepMedicRun", line 134, in <module>

  File "build/bdist.linux-x86_64/egg/deepmedic/frontEndModules/deepMedicTrain.py", line 496, in deepMedicTrainMain
  File "build/bdist.linux-x86_64/egg/deepmedic/trainValidateTestVisualiseParallel.py", line 1203, in do_training
TypeError: 'NoneType' object is not iterable
`

Short summary of my config:
- anisotropic 1x1x2.5 input images (on purpose to get a bigger receptive field in z-direction fyi)
- 3x3x3 kernels used only
- padding set to true
- train image segment sizes of 31x31x31, 33x33x33, 34x34x34, 35x35x35 all give this exact same error

Any idea what's causing this? I have no idea where the shape (1) comes from...

gr
Joeri

**Comment by Kamnitsask** [comment]
Hello Joeri,

First, let me ask you, when you resampled, did you also make sure to resample similarly the ROI mask and the GT labels? Cause a disagreement there could cause this kind of errors.

Second, debugging with parallel processing is quite a pain. Let us try to disable the parallel processing so that debugging becomes easier. Please go to the file  ./deepmedic/trainValidateTestVisualiseParallel.py and alter the following two lines:
if boolItIsTheVeryFirstSubepochOfThisProcess : ----> if True :
and
if (not performValidationOnSamplesDuringTrainingProcessBool) and boolItIsTheVeryFirstSubepochOfThisProcess : -------> if True :

The above should be enough to stop the pp parallel thread and instead do everything sequencially. Please let me know what error message you ll get then, hopefully will be a tiny bit more meaningful.

K

**Comment by gourie** [comment]
Tx for your quick reply Kostas, I just verified my preprocessing workflow and the label images had wrong dimensions (still my old 1x1x1 spacing)...

Busy building a new trainset now that hopefully corrects the problem...
Keep you posted if not.

gr
Joeri

**Comment by gourie** [comment]
Hi Kostas,

I generated a new trainset with the correct label images (spacing 1x1x2.5 equal to normroi, dimensions were already ok).
Unfortunately, the problem persists...

After changing the above two lines in ./deepmedic/trainValidateTestVisualiseParallel.py, this is the new error message:

```bash
TIMING: Extracting all the Segments for next Training took time: 229.77(s)
:=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Training. :=:=:=:=:=:=:=:=:
Traceback (most recent call last):
  File "/home/U052915a/anaconda2/bin/deepMedicRun", line 4, in <module>
    __import__('pkg_resources').run_script('deepmedic==0.6', 'deepMedicRun')
  File "/home/U052915a/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/U052915a/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/U052915a/anaconda2/lib/python2.7/site-packages/deepmedic-0.6-py2.7.egg/EGG-INFO/scripts/deepMedicRun", line 134, in <module>

  File "build/bdist.linux-x86_64/egg/deepmedic/frontEndModules/deepMedicTrain.py", line 496, in deepMedicTrainMain
  File "build/bdist.linux-x86_64/egg/deepmedic/trainValidateTestVisualiseParallel.py", line 1199, in do_training
  File "build/bdist.linux-x86_64/egg/deepmedic/trainValidateTestVisualiseParallel.py", line 856, in getTheArraysOfImageChannelsAndLesionsToLoadToGpuForSubepoch
  File "/home/U052915a/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (33,33,33) into shape (1)
```

Hope this helps...

gr,
Joeri

**Comment by gourie** [comment]
One last update Kostas: I experimentally discovered that the training runs without error when using train segment size 29x29x29. 
I cannot explain why but figured this might help you in understanding the above?

gr,
Joeri

**Comment by Kamnitsask** [comment]
Hello, sorry for the late reply.

The problem comes from ./deepmedic/trainValidateTestVisualiseParallel.py---> search for string "Finished extracting Segments from the images for next". The error comes from one of the two np.asarray() operations after it.

Both the below should be lists, that are being transformed to np arrays at these lines.
imagePartsChannelsToLoadOnGpuForSubepochPerPathway should be a list with 2 elements, one for each pathway.
Eg imPartsForPathwayi=imagePartsChannelsToLoadOnGpuForSubepochPerPathway[0] should have all the segments for the normal-resolution pathway for this subepoch. It should be a list, with 1000 elements (1000 segments per subepoch by default].
Each of the imPartsForPathwayi[j] should be a nparray, with shape = [29,29,29]

Similarly, gtLabelsForTheCentralPredictedPartOfSegmentsInGpUForSubepoch should be a list with 1000 elements (1 per segment), Each of these should be a nparray with [9,9,9] shape by default, but since you changed the input, probably larger ([13,13,13]?). 

What I believe happens is that, for some reason, when the segments are extracted, something goes wrong, and some of the segments are extracted [29,29,29] (correct), and some are not (eg the end of NaN or None or god knows what). So, when it tries to transform the list to a nparray, the error comes of broadcasting.

One thing you can do is, right after the "Finished extracting..." string, add the lines:

```
for imPartsForPathwayi in imagePartsChannelsToLoadOnGpuForSubepochPerPathway:
    for imagePart in imPartsForPathwayi:
        print "imagePart.shape=", imagePart.shape
```
You will get 1000 prints per subepoch, but you will be able to spot what goes wrong.

Then we can go backwards in the code to check where the problem lies. Could be a bug from my end, but first make sure that the data (GT/channels/roi masks) have exactly the same dimensions, cause often problems come from there.

Regards,
Kostas

K

**Comment by gourie** [comment]
Tx Kostas, I propose to run some detailed debugging conversations (with log files etc) offline and then update back the issue log with our conclusions :-)

First email sent.

gr,
Joeri

**Comment by SilvanaC** [comment]
@gourie I have a similar problem.... did you find the error?

**Comment by Kamnitsask** [comment]
Closing this for now as I have not observed this and has not been reported since.

In v0.7.0 I also added a check in the loading function, for example to check compatibility of the data (eg ground-truth label volumes) with the config parameters given for the model (eg number of classes) to report to the user an error if something inappropriate is found.

Closing, and lets see if anyone observes such a problem with the new Tensorflow backend version.
