### ISSUE TITLE
slow first run on a gpu

### ISSUE THREAD

**Issue by qumsiyeh13** [Kamnitsask/deepmedic#81]
ive noticed that the first testing/ training run on a gpu every couple of days or so takes a fairly long time (20 minutes for a normally 2 minute run), and the following runs revert back to 2 minutes. anyone else notice this or have an explanation as to why this might be occuring?
thanks
Kristofer

**Comment by Kamnitsask** [comment]
I am guessing this is because theano needs to compile certain things on the first run.

If you are on unix, check the folder ~/.theano, this is where those compiled files are kept. After that, next run on this machine would not need to recompile it, so it ll be faster. Except if you delete that hidden folder.

Perhaps every couple of days your system deletes certain files automatically, and recompilation is needed? Or you may need to recompile if you try to run theano on a different machine.

Google theano issues like this: https://stackoverflow.com/questions/34709181/theano-takes-a-few-minutes-to-start-a-script-running-on-gpu
